export enum EngineState {
  CREATED = "CREATED",
  INITIALIZING = "INITIALIZING",
  INITIALIZED = "INITIALIZED",
  RUNNING = "RUNNING",
  STOPPING = "STOPPING",
  STOPPED = "STOPPED",
  ERROR = "ERROR"
}